import { v4 as uuidv4 } from 'uuid';

const calendars = {
  personal: {
    colorName: 'personal',
    lightColors: {
      main: '#f9d71c',
      container: '#fff5aa',
      onContainer: '#594800',
    },
    darkColors: {
      main: '#fff5c0',
      onContainer: '#fff5de',
      container: '#a29742',
    },
  },
  work: {
    colorName: 'work',
    lightColors: {
      main: '#f91c45',
      container: '#ffd2dc',
      onContainer: '#59000d',
    },
    darkColors: {
      main: '#ffc0cc',
      onContainer: '#ffdee6',
      container: '#a24258',
    },
  },
  leisure: {
    colorName: 'leisure',
    lightColors: {
      main: '#1cf9b0',
      container: '#dafff0',
      onContainer: '#004d3d',
    },
    darkColors: {
      main: '#c0fff5',
      onContainer: '#e6fff5',
      container: '#42a297',
    },
  },
  school: {
    colorName: 'school',
    lightColors: {
      main: '#1c7df9',
      container: '#d2e7ff',
      onContainer: '#002859',
    },
    darkColors: {
      main: '#c0dfff',
      onContainer: '#dee6ff',
      container: '#426aa2',
    },
  },
};

export const createdEvents = [
    {
        id: uuidv4(),
        resourceId: 'Instructor Dean',
        title: 'Phyton course',
        start: '2025-01-13',
        end: '2025-01-17',
        weekCount: 3,
        singleDayEvent: false,
        calendars: [calendars.school],
        
    },
    {
        id: uuidv4(),
        resourceId: 'Professor Rio',
        title: 'Flash Event 2',
        start: '2025-01-13',
        end: '2025-01-24',
        weekCount: 0,
        singleDayEvent: true,
        calendars: [calendars.leisure],
    },
    {
        id: uuidv4(),
        resourceId: 'Beth Boland',
        title: 'Master Course 1',
        start: '2025-01-24',
        end: '2025-01-31',
        weekCount: 12,
        singleDayEvent: false,
        calendars: [calendars.school],
    },
    {
        id: uuidv4(),
        resourceId: 'Professor Rio',
        title: 'Master Course 2',
        start: '2025-01-13',
        end: '2025-02-15',
        weekCount: 5,
        singleDayEvent: false,
        calendars: [calendars.leisure],
    },
    {
        id: uuidv4(),
        resourceId: 'Instructor Smith',
        title: 'Master Course 3',
        start: '2025-01-13',
        end: '2025-01-31',
        weekCount: 3,
        singleDayEvent: false,
        calendars: [calendars.work],
    },
    {
        id: uuidv4(),
        resourceId: 'Professor Jane',
        title: 'Master Course 4',
        start: '2025-01-13',
        end: '2025-01-31',
        weekCount: 3,
        singleDayEvent: false,
        calendars: [calendars.leisure],
    },
    {
        id: uuidv4(),
        resourceId: 'Instructor Dean',
        title: 'Master Course 5',
        start: '2025-01-13',
        end: '2025-01-31',
        weekCount: 3,
        singleDayEvent: false,
        calendars: [calendars.personal],
    },
    {
        id: uuidv4(),
        resourceId: 'Instructor Dean',
        title: 'Master Course 6',
        start: '2025-01-13',
        end: '2025-01-31',
        weekCount: 3,
        singleDayEvent: false,
        calendars: [calendars.personal],
    },
    {
        id: uuidv4(),
        resourceId: 'Professor Rio',
        title: 'Master Course 7',
        start: '2025-01-13',
        end: '2025-01-31',
        weekCount: 3,
        singleDayEvent: false,
        calendars: [calendars.leisure],
    },
    {
        id: uuidv4(),
        resourceId: 'Beth Boland',
        title: 'Master Course 8',
        start: '2025-01-13',
        end: '2025-01-31',
        weekCount: 3,
        singleDayEvent: false,
        calendars: [calendars.school],
    },
    {
        id: uuidv4(),
        resourceId: 'Instructor Smith',
        title: 'Master Course 9',
        start: '2025-01-13',
        end: '2025-01-31',
        weekCount: 3,
        singleDayEvent: false,
        calendars: [calendars.work],
    },
    {
        id: uuidv4(),
        resourceId: 'Professor Jane',
        title: 'Master Course 10',
        start: '2025-01-13',
        end: '2025-01-31',
        weekCount: 3,
        singleDayEvent: false,
        calendars: [calendars.leisure],
    }
];
